use_frameworks!

platform :ios, '8.0'

target 'JTWebKitLib_Example' do
  pod 'JTWebKitLib', :path => '../'

  target 'JTWebKitLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
